

class LocalizerZH():

    # 保留
    switch_language: str = (
        "请选择应用语言，新的语言设置将在下次启动时生效 …"
        "\n"
        "Select application language, changes will take effect on restart …"
    )
    switch_language_toast: str = (
        "应用语言切换成功，请重启应用生效 …"
        "\n"
        "Language switched successfully, please restart the application for changes to take effect …"
    )

    # 通用
    add: str = "新增"
    edit: str = "修改"
    none: str = "无"
    back: str = "返回"
    next: str = "下一个"
    stop: str = "停止"
    start: str = "开始"
    timer: str = "定时器"
    close: str = "关闭"
    alert: str = "提醒"
    warning: str = "警告"
    confirm: str = "确认"
    cancel: str = "取消"
    auto: str = "自动"
    wiki: str = "功能说明"
    open: str = "打开"
    select: str = "选择"
    inject: str = "注入"
    filter: str = "过滤"
    search: str = "搜索"
    generate: str = "生成"
    placeholder: str = "请输入关键词 …"
    task_success: str = "任务执行成功 …"
    alert_no_data: str = "没有有效数据 …"
    alert_reset_timer: str = "将重置定时器，是否确认 … ？"
    alert_reset_translation: str = "将重置尚未完成的翻译任务，是否确认开始新的翻译任务 … ？"

    # 主页面
    app_close_message_box: str = "确定是否退出程序 … ？"
    app_new_version: str = "点击下载更新版本！"
    app_new_version_toast: str = "已找到新版本，版本号为 {VERSION}，请点击左下角按钮下载更新 …"
    app_new_version_update: str = "正在下载 {PERCENT} …"
    app_new_version_failure: str = "新版本下载失败 … "
    app_new_version_success: str = "新版本下载成功 … "
    app_new_version_downloaded: str = "点击应用新版本！"
    app_new_version_waiting_restart: str = "更新完成，应用即将关闭 …"
    app_theme_btn: str = "变换自如"
    app_language_btn: str = "字字珠玑"
    app_settings_page: str = "应用设置"
    app_platform_page: str = "接口管理"
    app_project_page: str = "项目设置"
    app_translation_page: str = "开始翻译"
    app_basic_settings_page: str = "基础设置"
    app_expert_settings_page: str = "专家设置"
    app_glossary_page: str = "术语表"
    app_text_preserve_page: str = "文本保护"
    app_text_replacement_page: str = "文本替换"
    app_pre_translation_replacement_page: str = "译前替换"
    app_post_translation_replacement_page: str = "译后替换"
    app_custom_prompt_navigation_item: str = "自定义提示词"
    app_custom_prompt_zh_page: str = "中文提示词"
    app_custom_prompt_en_page: str = "英文提示词"
    app_laboratory_page: str = "实验室"
    app_treasure_chest_page: str = "百宝箱"

    # 路径
    path_bilingual: str = "双语对照"
    path_glossary_export: str = "导出_术语表"
    path_text_preserve_export: str = "导出_文本保护"
    path_pre_translation_replacement_export: str = "导出_译前替换"
    path_post_translation_replacement_export: str = "导出_译后替换"
    path_result_check_kana: str = "结果检查_假名残留.json"
    path_result_check_hangeul: str = "结果检查_谚文残留.json"
    path_result_check_text_preserve: str = "结果检查_文本保护.json"
    path_result_check_similarity: str = "结果检查_相似度较高.json"
    path_result_check_glossary: str = "结果检查_术语表未生效.json"
    path_result_check_untranslated: str = "结果检查_未翻译的条目.json"
    path_result_check_retry_count_threshold: str = "结果检查_重试次数达到阈值.json"
    path_result_batch_correction: str = "批量修正.xlsx"
    path_result_name_field_extraction: str = "姓名字段提取.xlsx"

    # 日志
    log_proxy: str = "网络代理已启用 …"
    log_expert_mode: str = "专家模式已启用 …"
    log_api_test_fail: str = "接口测试失败 … "
    log_task_fail: str = "翻译任务失败 …"
    log_read_file_fail: str = "文件读取失败 …"
    log_write_file_fail: str = "文件写入失败 …"
    log_read_cache_file_fail: str = "从文件读取缓存数据失败 …"
    log_write_cache_file_fail: str = "向文件写入缓存数据失败 …"
    log_crash: str = "出现严重错误，程序即将退出，错误信息已保存至日志文件 …"
    cli_verify_folder: str = "参数发生错误：无效的路径 …"
    cli_verify_language: str = "参数发生错误：无效的语言 …"
    translator_max_round: str = "最大轮次"
    translator_current_round: str = "当前轮次"
    translator_api_url: str = "接口地址"
    translator_name: str = "接口名称"
    translator_model: str = "模型名称"
    translator_writing: str = "正在写入翻译数据，等稍候 …"
    translator_done: str = "所有文本均已翻译，翻译任务已结束 …"
    translator_fail: str = "已到最大翻译轮次，仍有部分文本未翻译，请检查翻译结果 …"
    translator_stop: str = "翻译任务已停止 …"
    translator_write: str = "翻译结果已保存至 {PATH} 目录 …"
    translator_task_generation_log: str = "任务生成已完成，共生成 {COUNT} 个任务 …"
    translator_rule_filter_log: str = "规则过滤已完成，共过滤 {COUNT} 个无需翻译的条目 …"
    translator_language_filter_log: str = "语言过滤已完成，共过滤 {COUNT} 个不包含目标语言的条目 …"
    translator_mtool_optimizer_pre_log: str = "MToolOptimizer 预处理已完成，共过滤 {COUNT} 个包含重复子句的条目 …"
    translator_mtool_optimizer_post_log: str = "MToolOptimizer 后处理已完成 …"
    translator_task_response_think: str = "模型思考内容：\n"
    translator_task_response_result: str = "模型回复内容：\n"
    translator_response_check_fail: str = "译文文本未通过检查，将在下一轮次的翻译中自动重试"
    translator_response_check_fail_all: str = "全部译文文本未通过检查，将在下一轮次的翻译中自动重试"
    translator_response_check_fail_part: str = "部分译文文本未通过检查，将在下一轮次的翻译中自动重试"
    translator_task_success: str = "任务耗时 {TIME} 秒，文本行数 {LINES} 行，输入消耗 {PT} Tokens，输出消耗 {CT} Tokens"
    translator_too_many_task: str = "实时任务数较多，暂时停止显示详细结果以提升性能 …"
    translator_no_items: str = "没有找到需要翻译的数据，请确认输入文件与项目设置是否正确 …"
    translator_running: str = "任务正在执行中，请稍后再试 …"
    file_checker_kana: str = "已完成假名残留检查，未发现异常条目 …"
    file_checker_kana_full: str = "已完成假名残留检查，发现 {COUNT} 个异常条目，占比为 {PERCENT} %，结果已写入 [green]{TARGET}[/] …"
    file_checker_hangeul: str = "已完成谚文残留检查，未发现异常条目 …"
    file_checker_hangeul_full: str = "已完成谚文残留检查，发现 {COUNT} 个异常条目，占比为 {PERCENT} %，结果已写入 [green]{TARGET}[/] …"
    file_checker_text_preserve: str = "已完成文本保护检查，未发现异常条目 …"
    file_checker_text_preserve_full: str = "已完成文本保护检查，发现 {COUNT} 个异常条目，占比为 {PERCENT} %，结果已写入 [green]{TARGET}[/] …"
    file_checker_text_preserve_alert_key: str = "____提醒____"
    file_checker_text_preserve_alert_value: str = "本文件内列出的是文本保护 **可能** 未生效的条目，请结合上下文语境进行实际判断！"
    file_checker_similarity: str = "已完成相似度异常检查，未发现异常条目 …"
    file_checker_similarity_full: str = "已完成相似度异常检查，发现 {COUNT} 个异常条目，占比为 {PERCENT} %，结果已写入 [green]{TARGET}[/] …"
    file_checker_similarity_alert_key: str = "____提醒____"
    file_checker_similarity_alert_value: str = "本文件内列出的是 **可能** 存在相似度较高情况的条目，请结合上下文语境进行实际判断！"
    file_checker_glossary: str = "已完成未生效术语检查，未发现异常条目 …"
    file_checker_glossary_full: str = "已完成未生效术语检查，发现 {COUNT} 个异常条目，占比为 {PERCENT} %，结果已写入 [green]{TARGET}[/] …"
    platofrm_tester_key: str = "正在测试密钥"
    platofrm_tester_messages: str = "任务提示词："
    platofrm_tester_response_think: str = "模型思考内容："
    platofrm_tester_response_result: str = "模型返回结果："
    platofrm_tester_result: str = "共测试 {COUNT} 个接口，成功 {SUCCESS} 个，失败 {FAILURE} 个 …"
    platofrm_tester_result_failure: str = "失败的密钥："
    platofrm_tester_running: str = "任务正在执行中，请稍后再试 …"
    response_checker_unknown: str = "未知"
    response_checker_fail_data: str = "数据结构错误"
    response_checker_fail_line_count: str = "行数不一致"
    response_checker_line_error_kana: str = "假名残留"
    response_checker_line_error_hangeul: str = "谚文残留"
    response_checker_line_error_fake_reply: str = "伪回复残留"
    response_checker_line_error_empty_line: str = "存在空行"
    response_checker_line_error_similarity: str = "较高相似度"
    response_checker_line_error_degradation: str = "发生退化现象"
    response_checker_line_error_source_residue: str = "源语言残留"
    response_checker_line_error_glossary_violation: str = "术语表未生效"
    response_decoder_glossary_by_json: str = "术语数据 -> 反序列化，共 {COUNT} 条"
    response_decoder_glossary_by_rule: str = "术语数据 -> 拆分后规则解析，共 {COUNT} 条"
    response_decoder_translation_by_json: str = "翻译数据 -> 反序列化，共 {COUNT} 条"
    response_decoder_translation_by_rule: str = "翻译数据 -> 拆分后规则解析，共 {COUNT} 条"

    # 应用设置
    app_settings_page_expert_title: str = "专家模式"
    app_settings_page_expert_content: str = "启用此功能后，将显示更多日志信息并提供更多高级设置选项（将在应用重启后生效）"
    app_settings_page_font_hinting_title: str = "字体优化"
    app_settings_page_font_hinting_content: str = "启用此功能后，应用内 UI 字体的边缘渲染将更加圆润（将在应用重启后生效）"
    app_settings_page_scale_factor_title: str = "全局缩放比例"
    app_settings_page_scale_factor_content: str = "启用此功能后，应用界面将按照所选比例进行缩放（将在应用重启后生效）"
    app_settings_page_proxy_url: str = "示例 - http://127.0.0.1:7890"
    app_settings_page_proxy_url_title: str = "网络代理"
    app_settings_page_proxy_url_content: str = "启用此功能后，将使用设置的代理地址发送网络请求（将在应用重启后生效）"
    app_settings_page_close: str = "应用即将关闭，请确认 …"

    # 接口管理
    platform_page_api_test_result: str = "接口测试结果：成功 {SUCCESS} 个，失败 {FAILURE} 个 …"
    platform_page_api_activate: str = "激活接口"
    platform_page_api_edit: str = "编辑接口"
    platform_page_api_args: str = "编辑参数"
    platform_page_api_test: str = "测试接口"
    platform_page_api_delete: str = "删除接口"
    platform_page_widget_add_title: str = "接口列表"
    platform_page_widget_add_content: str = "在此添加和管理任何兼容 Google、OpenAI、Anthropic 格式的 LLM 模型接口"

    # 接口编辑
    platform_edit_page_name: str = "请输入接口名称 …"
    platform_edit_page_name_title: str = "接口名称"
    platform_edit_page_name_content: str = "请输入接口名称，仅用于应用内显示，无实际作用"
    platform_edit_page_api_url: str = "请输入接口地址 …"
    platform_edit_page_api_url_title: str = "接口地址"
    platform_edit_page_api_url_content: str = "请输入接口地址，请注意辨别结尾是否需要添加 /v1"
    platform_edit_page_api_key: str = "请输入接口密钥 …"
    platform_edit_page_api_key_title: str = "接口密钥"
    platform_edit_page_api_key_content: str = "请输入接口密钥，例如 sk-d0daba12345678fd8eb7b8d31c123456，填入多个密钥可以轮询使用，每行一个"
    platform_edit_page_thinking_title: str = "优先使用思考模式"
    platform_edit_page_thinking_content: str = "对于同时支持思考模式和普通模式的模型，优先使用思考模式"
    platform_edit_page_model: str = "请输入模型名称 …"
    platform_edit_page_model_title: str = "模型名称"
    platform_edit_page_model_content: str = "当前使用的模型为 {MODEL}"
    platform_edit_page_model_edit: str = "手动输入"
    platform_edit_page_model_sync: str = "在线获取"

    # 参数编辑
    args_edit_page_top_p_title: str = "top_p"
    args_edit_page_top_p_content: str = "请谨慎设置，错误的值可能导致结果异常或者请求报错"
    args_edit_page_temperature_title: str = "temperature"
    args_edit_page_temperature_content: str = "请谨慎设置，错误的值可能导致结果异常或者请求报错"
    args_edit_page_presence_penalty_title: str = "presence_penalty"
    args_edit_page_presence_penalty_content: str = "请谨慎设置，错误的值可能导致结果异常或者请求报错"
    args_edit_page_frequency_penalty_title: str = "frequency_penalty"
    args_edit_page_frequency_penalty_content: str = "请谨慎设置，错误的值可能导致结果异常或者请求报错"
    args_edit_page_document_link: str = "点击查看文档"

    # 模型列表
    model_list_page_title: str = "可用的模型列表"
    model_list_page_content: str = "点击选择要使用的模型"
    model_list_page_fail: str = "获取模型列表失败，请检查接口配置 …"

    # 项目设置
    project_page_source_language_title: str = "原文语言"
    project_page_source_language_content: str = "设置当前项目中输入文本的语言"
    project_page_target_language_title: str = "译文语言"
    project_page_target_language_content: str = "设置当前项目中输出文本的语言"
    project_page_input_folder_title: str = "输入文件夹"
    project_page_input_folder_content: str = "当前输入文件夹为"
    project_page_output_folder_title: str = "输出文件夹（不能与输入文件夹相同）"
    project_page_output_folder_content: str = "当前输出文件夹为"
    project_page_output_folder_open_on_finish_title: str = "任务完成时打开输出文件夹"
    project_page_output_folder_open_on_finish_content: str = "启用此功能后，将在任务完成时自动打开输出文件夹"
    project_page_traditional_chinese_title: str = "使用繁体输出中文"
    project_page_traditional_chinese_content: str = "启用此功能后，在译文语言设置为中文时，将使用繁体字形输出中文文本"

    # 开始翻译
    translation_page_status_idle: str = "无任务"
    translation_page_status_testing: str = "测试中"
    translation_page_status_translating: str = "翻译中"
    translation_page_status_stopping: str = "停止中"
    translation_page_indeterminate_saving: str = "缓存文件保存中 …"
    translation_page_indeterminate_stoping: str = "正在停止翻译任务 …"
    translation_page_card_time: str = "累计时间"
    translation_page_card_remaining_time: str = "剩余时间"
    translation_page_card_line: str = "翻译行数"
    translation_page_card_remaining_line: str = "剩余行数"
    translation_page_card_speed: str = "平均速度"
    translation_page_card_token: str = "累计消耗"
    translation_page_card_task: str = "实时任务数"
    translation_page_alert_pause: str = "停止的翻译任务可以随时继续翻译，是否确定停止任务 … ？"
    translation_page_continue: str = "继续任务"
    translation_page_export: str = "导出任务数据"
    translation_page_timer: str = "请设置延迟启动前要等待的时间"

    # 基础设置
    basic_settings_page_max_workers_title: str = "并发任务阈值"
    basic_settings_page_max_workers_content: str = (
        "同时执行的任务数量的最大值"
        "<br>"
        "合理设置可以显著加快任务的完成速度，请参考 API 平台的文档进行设置，0 = 自动"
        ""
        ""
    )
    basic_settings_page_rpm_threshold_title: str = "每分钟任务数量阈值"
    basic_settings_page_rpm_threshold_content: str = (
        "每分钟执行的任务总数量的最大值，即 <font color='darkgoldenrod'><b>RPM</b></font> 阈值"
        "<br>"
        "部分平台会对网络请求的速率进行限制，请参考 API 平台的文档进行设置，0 = 无限制"
        ""
        ""
    )
    basic_settings_page_token_threshold_title: str = "任务长度阈值"
    basic_settings_page_token_threshold_content: str = "每个任务所包含的文本的最大 Token 数量"
    basic_settings_page_request_timeout_title: str = "超时时间阈值"
    basic_settings_page_request_timeout_content: str = (
        "发起请求时等待模型回复的最长时间（秒），超时仍未收到回复，则会判断为任务失败"
        ""
        ""
    )
    basic_settings_page_max_round_title: str = "任务轮次阈值"
    basic_settings_page_max_round_content: str = "当完成一轮任务后，将在新的轮次中对失败的任务进行重试，直到全部完成或达到轮次阈值"

    # 专家设置
    expert_settings_page_preceding_lines_threshold: str = "参考上文行数阈值"
    expert_settings_page_preceding_lines_threshold_desc: str = "每个翻译任务最多可携带的参考上文的行数，默认禁用"
    expert_settings_page_preceding_disable_on_local: str = "本地接口启用参考上文"
    expert_settings_page_preceding_disable_on_local_desc: str = "本地模型性能较差，参考上文功能大部分时候是负面效果，默认禁用"
    expert_settings_page_clean_ruby: str = "清理原文中的注音文本"
    expert_settings_page_clean_ruby_desc: str = (
        "移除注音上标中的注音部分，仅保留正文部分，默认启用"
        "<br>"
        "文本中的注音上标通常不能被模型正确理解，进行清理可以提升翻译质量，支持的注音格式包括但不限于："
        "<br>"
        "• (漢字/かんじ) [漢字/かんじ] |漢字[かんじ]"
        "<br>"
        "• \\r[漢字,かんじ] \\rb[漢字,かんじ] [r_かんじ][ch_漢字] [ch_漢字]"
        "<br>"
        "• [ruby text=かんじ] [ruby text = かんじ] [ruby text=\"かんじ\"] [ruby text = \"かんじ\"]"
        ""
        ""
    )
    expert_settings_page_deduplication_in_trans: str = "T++ 项目文件中对重复文本去重"
    expert_settings_page_deduplication_in_trans_desc: str = "在T++ 项目文件（即 <font color='darkgoldenrod'><b>.trans</b></font> 文件）中，如有重复文本是否去重，默认启用"
    expert_settings_page_deduplication_in_bilingual: str = "双语输出文件中原文与译文一致的文本只输出一次"
    expert_settings_page_deduplication_in_bilingual_desc: str = "在字幕与电子书中，如目标文本的原文与译文一致是否只输出一次，默认启用"
    expert_settings_page_write_translated_name_fields_to_file: str = "将姓名字段译文写入输出文件"
    expert_settings_page_write_translated_name_fields_to_file_desc: str = (
        "部分 <font color='darkgoldenrod'><b>GalGame</b></font> 中，姓名字段数据与立绘、配音等资源文件绑定，翻译后会报错，此时可以关闭该功能，默认启用"
        "<br>"
        "支持格式："
        "<br>"
        "• RenPy 导出游戏文本（.rpy）"
        "<br>"
        "• VNTextPatch 或 SExtractor 导出带 name 字段的游戏文本（.json）"
        ""
        ""
    )
    expert_settings_page_result_checker_retry_count_threshold: str = "结果检查 - 重试次数达到阈值"
    expert_settings_page_result_checker_retry_count_threshold_desc: str = (
        "是否在结果检查报告里面输出 <font color='darkgoldenrod'><b>重试次数达到阈值</b></font> 的条目列表"
        "<br>"
        "• 在进行翻译结果检查时，如果重试达阈值依然未通过检查，就会取最后一次的结果"
        "<br>"
        "• 通过此功能，就可以逐一确认最后的取值实际上是否正确的"
    )

    # 质量类通用
    quality_import: str = "导入"
    quality_import_toast: str = "数据已导入 …"
    quality_export: str = "导出"
    quality_export_toast: str = "数据已导出到应用根目录 …"
    quality_save: str = "保存"
    quality_save_toast: str = "数据已保存 …"
    quality_merge_duplication: str = "已合并重复数据 …"
    quality_preset: str = "预设"
    quality_reset: str = "重置"
    quality_reset_toast: str = "数据已重置 …"
    quality_reset_alert: str = "是否确认重置为默认数据 … ？"
    quality_select_file: str = "选择文件"
    quality_select_file_type: str = "支持的数据格式 (*.json *.xlsx)"
    quality_delete_row: str = "删除行"
    quality_switch_regex: str = "切换正则模式"

    # 术语表
    glossary_page_head_title: str = "术语表"
    glossary_page_head_content: str = "通过在提示词中构建术语表来引导模型翻译，可实现统一翻译、矫正人称属性等功能"
    glossary_page_table_row_01: str = "原文"
    glossary_page_table_row_02: str = "译文"
    glossary_page_table_row_03: str = "描述"
    glossary_page_kg: str = "一键制作工具"

    # 文本保护
    text_preserve_page_head_title: str = "自定义文本保护规则"
    text_preserve_page_head_content: str = (
        "对文本中不需要翻译的代码段、控制字符、样式字符等文本进行保护，避免这些文本被错误的翻译"
        "<br>"
        "<font color='darkgoldenrod'><b>默认禁用</b></font>，启用前请仔细阅读 <font color='darkgoldenrod'><b>Wiki</b></font> 中的功能说明以确保充分理解使用方式"
        "<br>"
        "• 启用 - 根据本页中设置的 <font color='darkgoldenrod'><b>正则规则</b></font> 匹配对应的文本进行保护"
        "<br>"
        "• 禁用 - 自动判断文本格式与游戏引擎，智能选择合适的保护规则，在大部分内容中都可以取得较好的效果"
    )
    text_preserve_page_table_row_01: str = "规则"
    text_preserve_page_table_row_02: str = "备注（仅作备忘，无实际作用）"

    # 译前替换
    pre_translation_replacement_page_head_title: str = "译前替换"
    pre_translation_replacement_page_head_content: str = (
        "在翻译开始前，将原文中匹配的部分替换为指定的文本，执行的顺序为从上到下依次替换"
        "<br>"
        "对于 <font color='darkgoldenrod'><b>RPGMaker MV/MZ</b></font> 引擎的游戏："
        "<br>"
        "• 导入游戏目录的 <font color='darkgoldenrod'><b>data</b></font> 或者 <font color='darkgoldenrod'><b>www\\data</b></font> 文件夹内的 <font color='darkgoldenrod'><b>actors.json</b></font> 文件可以显著提升翻译质量"
        "<br>"
        "• 游戏中包含自定义姓名功能时需要进行特殊处理，请点击右下角按钮跳转并仔细阅读 <font color='darkgoldenrod'><b>Wiki</b></font> 相关页面中的说明"
    )
    pre_translation_replacement_page_table_row_01: str = "原文"
    pre_translation_replacement_page_table_row_02: str = "替换"
    pre_translation_replacement_page_table_row_03: str = "正则"

    # 译后替换
    post_translation_replacement_page_head_title: str = "译后替换"
    post_translation_replacement_page_head_content: str = "在翻译完成后，将译文中匹配的部分替换为指定的文本，执行的顺序为从上到下依次替换"
    post_translation_replacement_page_table_row_01: str = "原文"
    post_translation_replacement_page_table_row_02: str = "替换"
    post_translation_replacement_page_table_row_03: str = "正则"

    # 自定义提示词 - 中文
    custom_prompt_zh_page_head: str = "自定义中文提示词（不支持 SakuraLLM 模型）"
    custom_prompt_zh_page_head_desc: str = (
        "通过自定义提示词追加故事设定、行文风格等额外翻译要求"
        "<br>"
        "注意：前缀与后缀部分固定不可修改，只有 <font color='darkgoldenrod'><b>译文语言设置为中文时</b></font> 才会使用本页中的自定义提示词"
        ""
        ""
    )

    # 自定义提示词 - 英文
    custom_prompt_en_page_head: str = "自定义英文提示词（不支持 SakuraLLM 模型）"
    custom_prompt_en_page_head_desc: str = (
        "通过自定义提示词追加故事设定、行文风格等额外翻译要求"
        "<br>"
        "注意：前缀与后缀部分固定不可修改，只有 <font color='darkgoldenrod'><b>译文语言设置为非中文时</b></font> 才会使用本页中的自定义提示词"
        ""
        ""
    )

    # 实验室
    laboratory_page_mtool_optimizer_enable: str = "MTool 优化器"
    laboratory_page_mtool_optimizer_enable_desc: str = (
        "在对 MTool 文本进行翻译时，至多可减少 40% 的 翻译时间 与 Token 消耗"
        "<br>"
        "可能导致 <font color='darkgoldenrod'><b>原文残留</b></font> 或 <font color='darkgoldenrod'><b>语句不连贯</b></font> 等问题，请 <font color='darkgoldenrod'><b>自行判断</b></font> 是否启用，并且只应在 <font color='darkgoldenrod'><b>翻译 MTool 文本时</b></font> 启用"
        ""
        ""
        ""
        ""
        ""
        ""
    )
    laboratory_page_auto_glossary_enable: str = "自动补全术语表（不支持 SakuraLLM 模型）"
    laboratory_page_auto_glossary_enable_desc: str = (
        "翻译的同时尝试自动补全术语表中缺失的专有名词条目，只有在 <font color='darkgoldenrod'><b>启用术语表功能</b></font> 时才生效"
        "<br>"
        "此功能设计目的仅为查漏补缺，并不能代替 <font color='darkgoldenrod'><b>KeywordGacha</b></font>，获取到的补充术语将直接 <font color='darkgoldenrod'><b>写入术语表</b></font>"
        "<br>"
        "可能会产生 <font color='darkgoldenrod'><b>不正确或不合适的术语条目</b></font>，请 <font color='darkgoldenrod'><b>自行判断</b></font> 是否启用，建议仅在 DeepSeek V3/R1 级别的强力模型使用此功能"
        ""
        ""
        ""
        ""
    )

    # 百宝箱
    tool_box_page_batch_correction: str = "批量修正"
    tool_box_page_batch_correction_desc: str = "根据翻译完成时生成的结果检查文件中的数据，对可能存在的翻译错误进行批量修正，实现快速修正译文结果的目的"
    tool_box_page_re_translation: str = "部分重翻"
    tool_box_page_re_translation_desc: str = "根据设置的筛选条件，重新对已完成的翻译文本中的部分内容进行翻译，主要用于内容的更新或错误的修正"
    tool_box_page_name_field_extraction: str = "姓名字段提取"
    tool_box_page_name_field_extraction_desc: str = (
        "提取 <font color='darkgoldenrod'><b>RenPy</b></font> 和 <font color='darkgoldenrod'><b>GalGame</b></font> 游戏文本中的角色姓名字段数据，"
        "自动生成对应的术语表数据，方便后续进行翻译"
    )

    # 百宝箱 - 批量修正
    batch_correction_page: str = "批量修正"
    batch_correction_page_desc: str = (
        "根据翻译完成时生成的结果检查文件中的数据，对可能存在的翻译错误进行批量修正，然后生成修正后的译文文件"
        "<br>"
        "工作流程："
        "<br>"
        "• 从 <font color='darkgoldenrod'><b>输入文件夹</b></font> 的翻译结果检查文件中提取可能需要修正的数据"
        "<br>"
        "• 检查提取出的数据，并根据实际情况对需要修正的条目进行修正"
        "<br>"
        "• 将修正后的数据注入 <font color='darkgoldenrod'><b>输入文件夹</b></font> 中的译文文件，然后在 <font color='darkgoldenrod'><b>输出文件夹</b></font> 生成修正后的译文文件"
    )
    batch_correction_page_step_01: str = "第一步 - 生成修正数据"
    batch_correction_page_step_01_desc: str = (
        "从结果检查文件中提取可能包含翻译错误的数据"
        "<br>"
        f"然后自动在 <font color='darkgoldenrod'><b>输出文件夹</b></font> 内生成用于编辑的数据文件 <font color='darkgoldenrod'><b>{path_result_batch_correction}</b></font>"
    )
    batch_correction_page_step_02: str = "第二步 - 注入修正数据"
    batch_correction_page_step_02_desc: str = (
        "检查数据文件中的内容，确认无误后 <font color='darkgoldenrod'><b>关闭</b></font> 文件，开始注入"
        "<br>"
        "请注意："
        "<br>"
        "• 除 <font color='darkgoldenrod'><b>修正列</b></font> 以外，不要修改数据文件内的其他数据"
        "<br>"
        "• 部分格式的译文文件名中会包含类似 <font color='darkgoldenrod'><b>.zh</b></font> 的语言后缀，在注入前请从文件名中移除语言后缀以正确匹配数据"
    )
    batch_correction_page_title_01: str = "文件名"
    batch_correction_page_title_02: str = "错误类型"
    batch_correction_page_title_03: str = "原文（勿修改此列）"
    batch_correction_page_title_04: str = "译文（勿修改此列）"
    batch_correction_page_title_05: str = "修正（请修改此列）"

    # 百宝箱 - 部分重翻
    re_translation_page: str = "部分重翻"
    re_translation_page_desc: str = (
        "将根据设置的筛选条件对 <font color='darkgoldenrod'><b>输入文件夹</b></font> 中的文本进行筛选，然后对符合条件的文本进行重翻"
        "<br>"
        "工作流程："
        "<br>"
        "• 分别从 <font color='darkgoldenrod'><b>输入文件夹</b></font> 的 <font color='darkgoldenrod'><b>src</b></font> 与 <font color='darkgoldenrod'><b>dst</b></font> 子目录中读取原文与译文"
        "<br>"
        "• 原文文件和译文文件的文件名和文件内容必须严格一一对应"
        "<br>"
        "• 根据本页中的设置筛选出需要重翻的文本，按正常流程进行翻译，翻译完成后输出更新后的译文文件"
    )
    re_translation_page_white_list: str = "关键字 - 白名单"
    re_translation_page_white_list_desc: str = (
        "包含这些关键字的文本将被重新翻译，可以填入多个关键字，每行一个，只需要命中其中之一即判断为需要重翻的文本"
        ""
        ""
    )
    re_translation_page_alert_not_equal: str = "原文与译文的行数不匹配 …"

    # 百宝箱 - 姓名字段提取
    name_field_extraction_page: str = "姓名字段提取"
    name_field_extraction_page_desc: str = (
        "将从 <font color='darkgoldenrod'><b>输入文件夹</b></font> 中所有符合条件的文件中提取角色姓名字段，自动生成对应的术语表数据"
        "<br>"
        "请注意：此功能 <font color='darkgoldenrod'><b>不能提取正文内的术语</b></font>，不能代替 <font color='darkgoldenrod'><b>KeywordGacha</b></font> 工具"
        "<br>"
        "支持格式："
        "<br>"
        "• RenPy 导出游戏文本（.rpy）"
        "<br>"
        "• VNTextPatch 或 SExtractor 导出带 name 字段的游戏文本（.json）"
    )
    name_field_extraction_page_step_01: str = "第一步 - 提取数据"
    name_field_extraction_page_step_01_desc: str = (
        "提取姓名字段及与其相关的上下文，发送至翻译器进行翻译"
        "<br>"
        f"翻译完成后，将在 <font color='darkgoldenrod'><b>输出文件夹</b></font> 内生成 <font color='darkgoldenrod'><b>{path_result_name_field_extraction}</b></font> 文件"
    )
    name_field_extraction_page_step_02: str = "第二步 - 生成术语表"
    name_field_extraction_page_step_02_desc: str = (
        f"将从 <font color='darkgoldenrod'><b>输出文件夹</b></font> 内的 <font color='darkgoldenrod'><b>{path_result_name_field_extraction}</b></font> 文件中提取翻译后的数据"
        "<br>"
        "然后生成对应的术语表数据，请注意检查生成的术语表数据是否正确"
    )